[server]
head = """
<meta name="google-site-verification" content="JVHHkwdTC5NTDYRH0vI1vZ6NEu4PLBRjAt1b8shi12A" />
<meta name="google-site-verification" content="googleb97b37c701930e06" />
"""
enableStaticServing = true
